using System.Collections.Generic;
using UnityEngine;

public class RouletteUI : MonoBehaviour
{
    [SerializeField] private float minSpinPower, maxSpinPower;
    [SerializeField] private float minStopPower, maxStopPower;
    [SerializeField] private float maxAngularVelocity = 1440;

    [SerializeField] private List<int> prizeList;

    private Rigidbody2D rb;

    private bool canGetPrize;

    private void Start()
    {
        rb = GetComponent<Rigidbody2D>();
    }

    private void Update()
    {
        FortuneWheelUpdate();
    }

    private void FortuneWheelUpdate()
    {
        var angularVelocity = rb.angularVelocity;

        if (angularVelocity > 0)
        {
            angularVelocity -= Random.Range(minStopPower, maxStopPower) * Time.deltaTime;
            if (angularVelocity < 5)
            {
                angularVelocity = 0;
            }
            rb.angularVelocity = angularVelocity;

            rb.angularVelocity = Mathf.Clamp(angularVelocity, 0, maxAngularVelocity);

            canGetPrize = true;
        }

        if (angularVelocity > 0 || !canGetPrize) 
            return;
        
        GetRewardPosition();
    }
    
    public void SpinWheel()
    {
        if (rb.angularVelocity > 0) 
            return;
        
        rb.AddTorque(Random.Range(minSpinPower, maxSpinPower));
    }

    private void GetRewardPosition()
    {
        var rotationAngle = transform.eulerAngles.z;
        var pieSize = (360f / prizeList.Count);
        int priceIndex = Mathf.FloorToInt((rotationAngle+22.5f) / pieSize) % prizeList.Count;
        GetPrize(prizeList[priceIndex]);
    }

    private void GetPrize(int score)
    {
        Debug.Log(score);
        canGetPrize = false;
    }
}
